CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    icon VARCHAR(255) NOT NULL DEFAULT 'GENERAL',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    has_variants BOOLEAN NOT NULL DEFAULT FALSE,
    variant_type VARCHAR(255),
    variant_selection_required BOOLEAN NOT NULL DEFAULT FALSE,
    variant_selection_mode VARCHAR(255) NOT NULL DEFAULT 'SINGLE'
);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_time TIMESTAMP,
    ready_at TIMESTAMP,
    finished_at TIMESTAMP,
    paid_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    status VARCHAR(255),
    payment_status VARCHAR(255),
    payment_method VARCHAR(255),
    customer_name VARCHAR(255),
    customer_phone_number VARCHAR(255),
    customer_team VARCHAR(255),
    total_value DOUBLE PRECISION,
    observation VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id),
    name VARCHAR(255) NOT NULL,
    available BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id),
    order_id BIGINT NOT NULL REFERENCES orders(id),
    quantity INTEGER,
    unit_price DOUBLE PRECISION,
    product_name VARCHAR(255) NOT NULL,
    selected_variant_id BIGINT,
    selected_variant_name VARCHAR(255),
    selected_variant_names VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS order_item_selected_variant_ids (
    order_item_id BIGINT NOT NULL REFERENCES order_items(id) ON DELETE CASCADE,
    variant_id BIGINT
);

ALTER TABLE products ADD COLUMN IF NOT EXISTS icon VARCHAR(255) NOT NULL DEFAULT 'GENERAL';
ALTER TABLE products ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS has_variants BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS variant_type VARCHAR(255);
ALTER TABLE products ADD COLUMN IF NOT EXISTS variant_selection_required BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS variant_selection_mode VARCHAR(255) NOT NULL DEFAULT 'SINGLE';

ALTER TABLE orders ADD COLUMN IF NOT EXISTS ready_at TIMESTAMP;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS finished_at TIMESTAMP;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS paid_at TIMESTAMP;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMP;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_name VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_phone_number VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_team VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS observation VARCHAR(500);

ALTER TABLE order_items ADD COLUMN IF NOT EXISTS product_name VARCHAR(255);
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS selected_variant_id BIGINT;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS selected_variant_name VARCHAR(255);
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS selected_variant_names VARCHAR(500);

UPDATE order_items oi
SET product_name = products.name
FROM products
WHERE oi.product_id = products.id
  AND oi.product_name IS NULL;

ALTER TABLE order_items ALTER COLUMN product_name SET NOT NULL;
ALTER TABLE products DROP COLUMN IF EXISTS stock_quantity;
